text_encoder: 'emilyalsentzer/Bio_ClinicalBERT'
disease_book: Sample_Finetuning_SIIMACR/I1_classification/data_file/observation explanation.json
data_path: /home/zuzanna/rsna/train
undersample: False
dataset: rsna

image_res: 224
batch_size: 64
test_batch_size: 64
num_classes: 1
d_model: 256
temp: 0.07
mlm_probability: 0.15
queue_size: 8192
momentum: 0.995
alpha: 0.4
res_base_model: 'resnet50'
N: 4
H: 4 
dropout: 0.1
attribute_set_size: 2
deformable: False

# optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.1}
# schedular: {sched: cosine, lr: 1e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 0, cooldown_epochs: 0}
# optimizer: {opt: adamW, lr: 5e-5, weight_decay: 0.01}
# schedular: {sched: cosine, lr: 5e-5, epochs: 20, min_lr: 1e-6, decay_rate: 1, warmup_lr: 5e-5, warmup_epochs: 2, cooldown_epochs: 0}
optimizer: {opt: adamW, lr: 5e-6, weight_decay: 0.01}
schedular: {sched: cosine, lr: 5e-6, epochs: 10, min_lr: 1e-7, decay_rate: 1, warmup_lr: 5e-6, warmup_epochs: 2, cooldown_epochs: 0}